=== emylyano3/futboltel/guibuilder/src/main/resources/gui.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="gui">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="buttons" type="buttons" maxOccurs="1" />
				<xsd:element name="text_areas" type="text_areas" maxOccurs="1" />
				<xsd:element name="text_fields" type="text_fields" maxOccurs="1" />
				<xsd:element name="check_boxes" type="check_boxes" maxOccurs="1" />
				<xsd:element name="combo_boxes" type="combo_boxes" maxOccurs="1" />
				<xsd:element name="binded_combos" type="binded_combos" maxOccurs="1" />
				<xsd:element name="labels" type="labels" maxOccurs="1" />
				<xsd:element name="panels" type="panels" maxOccurs="1" />
				<xsd:element name="menu_bars" type="menu_bars" maxOccurs="1" />
				<xsd:element name="state_bars" type="state_bars" maxOccurs="1" />
				<xsd:element name="tool_bars" type="tool_bars" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- Definicion de grupos de componentes-->

	<xsd:complexType name="buttons">
		<xsd:sequence>
			<xsd:element name="button" type="button" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="text_areas">
		<xsd:sequence>
			<xsd:element name="text_area" type="text_area" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="text_fields">
		<xsd:sequence>
			<xsd:element name="text_field" type="text_field" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="check_boxes">
		<xsd:sequence>
			<xsd:element name="check_box" type="check_box" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="combo_boxes">
		<xsd:sequence>
			<xsd:element name="combo_box" type="combo_box" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="binded_combos">
		<xsd:sequence>
			<xsd:element name="binded_combo" type="binded_combo" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="labels">
		<xsd:sequence>
			<xsd:element name="label" type="label" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="panels">
		<xsd:sequence>
			<xsd:element name="panel" type="panel" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="menu_bars">
		<xsd:sequence>
			<xsd:element name="menu_bar" type="menu_bar" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="state_bars">
		<xsd:sequence>
			<xsd:element name="state_bar" type="state_bar" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="tool_bars">
		<xsd:sequence>
			<xsd:element name="button" type="button" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Definicion de tipos de componentes -->
	
	<xsd:complexType name="gui_component">
		<xsd:attribute name="enabled" type="xsd:boolean" default="true" />
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="tool_tip" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="listenable">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="action_listener" type="xsd:string"	use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="button">
		<xsd:complexContent>
			<xsd:extension base="listenable">
				<xsd:attribute name="icon" type="xsd:string" />
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="text_area">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="text_field">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="check_box">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="combo_box">
		<xsd:complexContent>
			<xsd:extension base="listenable">
				<!-- Falta Completar -->
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="binded_combo">
		<xsd:complexContent>
			<xsd:extension base="listenable">
				<!-- Falta Completar -->
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="label">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="icon" type="xsd:string" />
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="panel">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="icon" type="xsd:string" />
				<xsd:attribute name="layout" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="menu_bar">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:sequence>
					<xsd:element name="menu" type="menu" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="menu">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:sequence>
					<xsd:element name="menu_item" type="menu_item" />
				</xsd:sequence>
				<xsd:attribute name="text" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="menu_item">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<xsd:attribute name="text" type="xsd:string" />
				<!-- Falta Completar -->
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="state_bar">
		<xsd:complexContent>
			<xsd:extension base="gui_component">
				<!-- Falta Completar -->
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== emylyano3/futboltel/guibuilder/src/main/resources/settings/guiTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<gui xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://svn3.xp-dev.com/svn/Futboltel/trunk/Implementacion/fulboltel/guibuilder/src/main/resources/gui.xsd">
	
	<buttons>
		<button name="Aceptar" action_listener="" icon="" text="Aceptar" tool_tip="Confirma el ingreso de datos" enabled="true"/>
		<button name="Cancelar" action_listener="" icon="" text="Cancelar" tool_tip="Cancela el ingreso de datos" enabled="true"/>
	</buttons>
		
	<text_fields>
		<text_field name="User" text="" tool_tip="Ingrese su nombre de usuario" enabled="true"/>
		<password_field name="Pass" text="" tool_tip="Ingrese su clave de usuario" enabled="true"/>
	</text_fields>
	
<!-- 
	<combo_boxes>
		<combo_box name="Dominio" list="futboltel, deportel" tool_tip="Elija el dominio" enabled="true"/>
	</combo_boxes>
 -->
	
	<labels>
		<label name="User" text="Nombre de usuario" icon="" tool_tip="" enabled="true"/>
		<label name="Pass" text="Contraseña" icon="" tool_tip="" enabled="true"/>
	</labels>

 	
	<panels>
		<panel name="General" text="" tool_tip="" enabled="true"/>
		<tabbed_panel name="General1" text="" tool_tip="" enabled="true"/>
	</panels>


	<menu_bars>
		<menu_bar name="Principal" tool_tip="Barra de menu de la ventana principal" enabled="true">
			<menu name="File" text="Archivo" tool_tip="" enabled="true" >
				<menu_item name="NewFile" text="New" tool_tip="" enabled="true" action_listener="" />
				<menu_item name="OpenFile" text="Open" tool_tip="" enabled="true" action_listener="" />
			</menu>
		</menu_bar>
	</menu_bars>
	
<!-- 	
	<state_bars>
		<state_bar name="Estado" enabled="true" tool_tip="Barra de estado"/>
	</state_bars>
 -->
 
</gui>

=== emylyano3/futboltel/backend/editores/templates/src/main/resources/settings/templateEditor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<gui xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://svn3.xp-dev.com/svn/Futboltel/trunk/Implementacion/fulboltel/guibuilder/src/main/resources/gui.xsd">

	<panels>
		<panel name="global" tool_tip="" layout="org.jdesktop.layout.GroupLayout"
			font_name="Arial" font_style="plain" font_size="13" border=""
			enabled="true" visible="true" />

		<!-- Importacion de XML -->
		<panel name="import" tool_tip="" layout="org.jdesktop.layout.GroupLayout"
			font_name="Arial" font_style="plain" font_size="13" border=""
			enabled="true" visible="false" />
		<panel name="importBrowse" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" font_name="Arial"
			font_style="bold" font_size="13" border="" enabled="true" visible="true" />
		<panel name="importDebrief" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" font_name="Arial"
			font_style="bold" font_size="13" border="" enabled="true" visible="true" />
		<panel name="importDebriefDetails" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" font_name="Arial"
			font_style="plain" font_size="13" border="" enabled="true" visible="true" />

		<!-- Creacion / Edicion de componente -->
		<panel name="componentCreateGlobal" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" border="" enabled="true"
			font_name="Arial" font_style="plain" font_size="13" visible="false" />
		<panel name="componentEdition" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" border="" enabled="true"
			font_name="Arial" font_style="bold" font_size="13" visible="true" />
		<panel name="componentEditionScroll" tool_tip=""
			layout="org.jdesktop.layout.GroupLayout" border="" enabled="true"
			font_name="Arial" font_style="plain" font_size="13" visible="true" />
		<panel name="componentSelection" tool_tip="" font_name="Arial"
			font_style="bold" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			border="" enabled="true" visible="true" />

		<!-- Edicion de imagenes -->
		<panel name="eiGlobal" tool_tip="" font_name="Arial" font_style="bold"
			font_size="13" layout="org.jdesktop.layout.GroupLayout" border=""
			enabled="true" visible="true" />
		<panel name="eiDetailsGeneral" tool_tip="" font_name="Arial"
			font_style="plain" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			border="" enabled="true" visible="true" />
		<panel name="eiDetails" tool_tip="" font_name="Arial"
			font_style="plain" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			border="" enabled="true" visible="true" />
		<panel name="eiTools" tool_tip="" font_name="Arial" font_style="plain"
			font_size="13" layout="org.jdesktop.layout.GroupLayout" border=""
			enabled="true" visible="true" />
		<panel name="eiSelection" tool_tip="" font_name="Arial"
			font_style="plain" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			border="" enabled="true" visible="true" />
	</panels>

	<binded_combos>
		<binded_combo name="selTema" font_name="Arial"
			font_style="plain" font_size="13" first_item_empty="true"
			tool_tip="Elija el tipo de componente a editar" list="" enabled="true"
			visible="true" action_listener="com.deportel.editor.template.view.listener.TEActionListener" />
		<binded_combo name="selTipoComponente" font_name="Arial"
			font_style="plain" font_size="13" first_item_empty="true"
			tool_tip="Elija el tipo de componente a editar" list="" enabled="false"
			visible="true" action_listener="com.deportel.editor.template.view.listener.TEActionListener" />
		<binded_combo name="selComponente" font_name="Arial"
			font_style="plain" font_size="13" first_item_empty="true"
			tool_tip="Elija el componente a editar" list="" enabled="false"
			visible="true" action_listener="com.deportel.editor.template.view.listener.TEActionListener" />
	</binded_combos>

	<labels>
		<label name="browse" text="Archivo de componentes" tool_tip=""
			font_name="Arial" font_style="plain" font_size="13" enabled="true"
			visible="true" />
		<label name="selTema" text="Tema de la aplicación" tool_tip=""
			font_name="Arial" font_style="plain" font_size="13" enabled="true"
			visible="true" />
		<label name="selTipoComponente" text="Tipo de componente a editar"
			tool_tip="" font_name="Arial" font_style="plain" font_size="13"
			enabled="true" visible="true" />
		<label name="selComponente" text="Componente a editar" tool_tip=""
			font_name="Arial" font_style="plain" font_size="13" enabled="true"
			visible="true" />
		<label name="importDebriefDetails" text="Componentes Cargados"
			tool_tip="" font_name="Arial" font_style="plain" font_size="13"
			enabled="true" visible="true" />
	</labels>

	<scroll_panes>
		<scroll_pane name="componentEdition" enabled="true"
			visble="false" />
		<scroll_pane name="importDebriefDetails" enabled="true"
			visble="false" />
		<scroll_pane name="eiDetails" enabled="true" visble="true" />
	</scroll_panes>

	<buttons>
		<button name="browse" text="Explorar" visible="true" enabled="true"
			tool_tip="Explorar el sistema de archivos"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="loadFile" text="Cargar" visible="true" enabled="true"
			tool_tip="Carga archivo el xml"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="okImport" text="Importar" visible="true" enabled="false"
			tool_tip="Importa el xml persistiendo los datos en la base"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="cancelImport" text="Cancelar" visible="true"
			enabled="false" tool_tip="Cancela la importación"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="cancelEdit" text="Cancelar" visible="true"
			enabled="true" tool_tip="Cancela la edición del componente"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="cancelImageEdit" text="Cancelar" visible="true"
			enabled="true" tool_tip="Cancela la edición de la imagen del componente"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="eiAddImage" text="Agregar" visible="true"
			enabled="true" tool_tip="Agrega los controles para ingresar  una nueva imagen"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="eiDone" text="Listo" visible="true" enabled="true"
			tool_tip="Finaliza la selección de sources"
			action_listener="com.deportel.editor.template.view.listener.TEActionListener"
			font_name="Arial" font_style="plain" font_size="13" />
		<button name="propEditDone" text="Listo" visible="true"
			enabled="true" tool_tip="Finaliza la edicion de la propiedad"
			font_name="Arial" font_style="plain" font_size="13" />
	</buttons>

	<text_fields>
		<text_field name="browse" visible="true" enabled="true" />
	</text_fields>

	<tool_bars>
		<tool_bar name="templatesEditor" tool_tip="" enabled="true"
			visible="true">
			<button name="tiMode" text="" icon="/images/import_icon.png"
				tool_tip="Importar componentes desde XML"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="true" visible="true" />
			<button name="ceNewMode" text="" icon="/images/new_icon.png"
				tool_tip="Crear un nuevo componente"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="false" visible="true" />
			<button name="ieMode" text="" icon="/images/images_icon.png"
				tool_tip="Editar imagenes"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="true" visible="true" />
			<button name="ceEditMode" text="" icon="/images/edit_icon.png"
				tool_tip="Editar componentes"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="true" visible="true" />
			<button name="ceDeleteMode" text="" icon="/images/delete_icon.png"
				tool_tip="Eliminar componentes"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="false" visible="true" />
			<button name="save" text="" icon="/images/save_icon.png"
				tool_tip="Guardar el componente"
				action_listener="com.deportel.editor.template.view.listener.TEActionListener"
				enabled="false" visible="false" />
		</tool_bar>
	</tool_bars>

	<check_boxes>
		<check_box name="paraContenido" text="Componentes para contenido"
			tool_tip="Seleccionar para importar como componentes para contenido"
			font_name="Arial" font_style="plain" font_size="13" selected="false"
			enabled="true" visible="true" action_listener="" />
	</check_boxes>
</gui>

=== emylyano3/futboltel/backend/editores/torneo/src/main/resources/settings/torneoEditor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<gui xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://svn3.xp-dev.com/svn/Futboltel/trunk/Implementacion/fulboltel/guibuilder/src/main/resources/gui.xsd">

	<panels>
		<panel name="panelContenedor" enabled="true" tool_tip=""/>
		<panel name="panelToolBar" enabled="true" tool_tip=""/>
		<panel name="panelStateBar" enabled="true" tool_tip=""/>
		<panel name="panelFiltros" enabled="true" tool_tip="" background="" border="blackline"/>
		<panel name="panelDatos" enabled="true" tool_tip=""/>
		<panel name="panelEventosLocal" enabled="true" tool_tip="" border="blackline"/>
		<panel name="panelEventosVisitante" enabled="true" tool_tip=""/>
		<panel name="panelPlantelLocal" enabled="true" tool_tip=""/>
		<panel name="panelPlantelVisitante" enabled="true" tool_tip=""/>
		<panel name="panelFiltrosTorneo" enabled="true" tool_tip=""/>
		<panel name="panelFiltrosFecha" enabled="true" tool_tip=""/>
		<panel name="panelSFiltrosPartido" enabled="true" tool_tip=""/>
		<panel name="panelDatosArbitro" enabled="true" tool_tip=""/>
		<panel name="panelDatosCancha" enabled="true" tool_tip=""/>
		<panel name="panelDatosHorario" enabled="true" tool_tip=""/>
		<panel name="panelDatosLocal" enabled="true" tool_tip=""/>
		<panel name="panelDatosVisitante" enabled="true" tool_tip=""/>
		<tabbed_panel name="tabbedContenedor" tool_tip="" enabled="true"/>
	</panels>
	
	
	<buttons>
		<button name="botonVolverFecha" text="Volver" enabled="true" tool_tip="Vuelve al filtro anterior" action_listener=""/>
		<button name="botonVolverPartido" text="Volver" enabled="true" tool_tip="Vuelve al filtro anterior" action_listener=""/>
		<button name="botonIngresarEventos" text="Ingresar eventos" enabled="false" tool_tip="Ingresar los eventos de los jugadores" action_listener=""/>
		<button name="botonGuardarEventosLocal" text="Confirmar" enabled="false" tool_tip="" action_listener=""/>
		<button name="botonGuardarEventosVisitante" text="Confirmar" enabled="false" tool_tip="" action_listener=""/>
		<button name="botonReiniciar" text="Reiniciar" enabled="false" tool_tip="" action_listener=""/>
		<button name="botonFinalizarVisitante" text="Finalizar" enabled="true" tool_tip="" action_listener=""/>
		<button name="botonActualizarBase" text="DAR DE ALTA" enabled="false" tool_tip="" action_listener=""/>				
	</buttons>
	
	<tool_bars>
		<tool_bar name="toolBarBotones" enabled="true" tool_tip="">
			<image_toogle_button name="toolAlta" text="Alta" enabled="true" tool_tip="" action_listener="" />
			<image_toogle_button name="toolModif" text="Modif." enabled="true" tool_tip="" action_listener="" />
			<image_toogle_button name="toolBaja" text="Baja" enabled="true" tool_tip="" action_listener="" />
			<image_toogle_button name="toolInfo" text="Info" enabled="true" tool_tip="" action_listener="" />
		</tool_bar>
	</tool_bars>
	
	<labels>
		<label name="labelTorneo" text="Torneo" icon="" tool_tip="" enabled="true"/>
		<label name="labelFecha" text="Fecha" icon="" tool_tip="" enabled="true"/>
		<label name="labelPartido" text="Partido" icon="" tool_tip="" enabled="true"/>
		<label name="labelArbitro" text="Arbitro" icon="" tool_tip="" enabled="false"/>
		<label name="labelHorario" text="Horario" icon="" tool_tip="" enabled="false"/>
		<label name="labelLocal" text="Local" icon="" tool_tip="" enabled="false" visible="false"/>
		<label name="labelVisitante" text="Visitante" icon="" tool_tip="" enabled="false" visible="true"/>
		<label name="labelCancha" text="Cancha" icon="" tool_tip="" enabled="false"/>
		<label name="labelPlantelLocal" text="Plantel Local" icon="" tool_tip="" enabled="true"/>
		<label name="labelPlantelVisitante" text="Plantel Visitante" icon="" tool_tip="" enabled="true"/>
	</labels>
	
	<text_fields>
		<text_field name="Arbitro" text="" tool_tip="" focus_listener="" enabled="false" visible="true" />
		<text_field name="Cancha" text="" tool_tip="" focus_listener="" enabled="false" visible="true" />
		<text_field name="Horario" text="" tool_tip="" focus_listener="" enabled="false" visible="true" />
		<text_field name="Local" text="" tool_tip="" focus_listener="" enabled="false" visible="true" />
		<text_field name="Visitante" text="" tool_tip="" focus_listener="" enabled="false" visible="true" />
	</text_fields>
	
	<tables>
		<table name="tablaLocal" column_names="" model="" enabled="true" visible="true"/>
		<table name="tablaVisitante" column_names="" model="" enabled="true" visible="true"/>
	</tables>
	
	
	<combo_boxes>
		<combo_box name="torneo" enabled="true" tool_tip="" list="" />
		<combo_box name="fecha" enabled="false" tool_tip="" list="" />
		<combo_box name="partido" enabled="false" tool_tip="" list="" />
	</combo_boxes>
</gui>

=== emylyano3/futboltel/seguridad/src/main/resources/settings/seguridad.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<gui xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://svn3.xp-dev.com/svn/Futboltel/trunk/Implementacion/fulboltel/guibuilder/src/main/resources/gui.xsd">

	<buttons>
		<button name="aceptar" action_listener="" icon="" text="Aceptar"
			font_name="Arial" font_style="plain" font_size="13"
			tool_tip="Confirma el ingreso de datos" enabled="true" />
		<button name="cancelar" action_listener="" icon="" text="Cancelar"
			font_name="Arial" font_style="plain" font_size="13"
			tool_tip="Cancela el ingreso de datos" enabled="true" />
		<button name="pr_confirm"
			action_listener="com.deportel.seguridad.view.listener.SeguridadActionListener"
			icon="" text="Confirmar" font_name="Arial" font_style="plain"
			font_size="13" tool_tip="Cancela el ingreso de datos" enabled="true" />
	</buttons>

	<text_fields>
		<text_field name="user" text="admin" tool_tip="Ingrese su nombre de usuario"
			font_name="Arial" font_style="plain" font_size="13" enabled="true" />
		<password_field name="pass" text="admin"
			font_name="Arial" font_style="plain" font_size="13"
			tool_tip="Ingrese su clave de usuario" enabled="true" text_limit="12" />
		<text_field name="pr_alias" text="" font_name="Arial"
			font_style="plain" font_size="13" tool_tip="Ingrese su nombre de usuario"
			enabled="true" text_limit="45" />
	</text_fields>

	<labels>
		<label name="user" text="Usuario" icon="" tool_tip="" font_name="Arial"
			font_style="plain" font_size="13" enabled="true" />
		<label name="pass" text="Contraseña" icon="" tool_tip=""
			font_name="Arial" font_style="plain" font_size="13" enabled="true" />
		<label name="forgot_pass" text="Olvidé mi constraseña" icon=""
			tool_tip="" font_name="Arial" font_style="plain" font_size="11"
			foreground_color="5555FF" enabled="true"
			mouse_listener="com.deportel.seguridad.view.listener.SeguridadMouseListener" />
		<label name="pr_alias" text="Usuario" icon="" tool_tip=""
			font_name="Arial" font_style="plain" font_size="13" enabled="true" />
	</labels>

	<panels>
		<panel name="general" text="" tool_tip="" font_name="Arial"
			font_style="bold" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			enabled="true" />
		<panel name="pr_general" text="" tool_tip="" font_name="Arial"
			font_style="bold" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			enabled="true" />
		<panel name="pr_input" text="" tool_tip="" font_name="Arial"
			font_style="bold" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			enabled="true" />
		<panel name="pr_confirm" text="" tool_tip="" font_name="Arial"
			font_style="bold" font_size="13" layout="org.jdesktop.layout.GroupLayout"
			enabled="true" />
	</panels>

</gui>
